baseURL = "https://example.org"

disableKinds = ["page", "section", "taxonomy", "term"]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.79.0"

[build]
# Used by PurgeCSS
writeStats = true