import Head from "next/head";
import Body from "./Body";
import Footer from "./Footer";
import Header from "./Header";

export default function BaseLayout({
  title = "Λογοθεραπεία",
  children,
  className = "",
}) {
  return (
    <Body>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={`flex-grow w-full mx-auto ${className}`}>{children}</div>
      <Footer />
    </Body>
  );
}
