import Head from "next/head";
import Body from "./Body";
import Footer from "./Footer";
import Header from "./Header";

export default function BaseLayout({ title = "Λογοθεραπεία", children }) {
  return (
    <Body>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="flex-grow w-full max-w-6xl mx-auto">{children}</div>
      <Footer />
    </Body>
  );
}
