import Head from "next/head";
import Footer from "./Footer";
import Header from "./Header";

export default function BaseLayout({ title = "Λογοθεραπεία", children }) {
  return (
    <div className="container flex flex-col h-screen max-w-full text-xl bg-my-white text-my-base font-body">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="flex-grow">{children}</div>
      <Footer />
    </div>
  );
}
