import Head from "next/head";
import Header from "../components/Header";

export default function Home() {
  return (
    <div className="container flex flex-col max-w-full min-h-screen text-xl selecti bg-my-white text-my-base font-body">
      <Head>
        <title>Λογοθεραπεία</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </div>
  );
}
